### ISSUE TITLE
Bug : recalculated values are not labelled with a star

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#105] opened 2019-09-02 06:39 UTC
Norway has no data in 2018 and 2019 and should be starred

**Comment by cedricbriandgithub** [comment] 2019-09-25 10:02
![image](https://user-images.githubusercontent.com/26055877/65591157-40f93480-df8c-11e9-9d24-c58bb2735062.png)
Theres still seems to be a problem (here glass eel) check

**Comment by cedricbriandgithub** [comment] 2019-10-24 08:03
bug : 
I also noted that the ‘landings comm corrected’ on the shiny app has small values for IE for 2018 and 2019, 0.449 and 0.055t respectively. As there are no commercial fisheries in Ireland these values should be 0, even when ‘corrected’. Of course, there is a tiny chance that trap and transport has got in the way but I am only speculating.

**Comment by elfunesto** [comment] 2020-05-14 09:51
For IE, the problem is that data are missing in recent years (dataframe landings stored in data/ref_and_eel_data.Rdata), therefore predictions are made and since IE used to have significant catches till 2008, glm predictions are not null. I think it would be better correcting the data @cedricbriandgithub ?

**Comment by elfunesto** [comment] 2020-05-14 09:55
For the first bug, I think that in server.R line 195
`table[,col][table2[,col]==0]<-paste0(table[,col][table2[,col]==0],"*")`
should be changed to 
`table[,col][table2[,col]==1]<-paste0(table[,col][table2[,col]==1],"*")`

**Comment by cedricbriandgithub** [comment] 2020-05-14 11:08
So it's just an inversion ?

**Comment by cedricbriandgithub** [comment] 2020-05-14 11:13
@elfunesto I have checked our notes for data integration in github https://github.com/ices-eg/wg_WGEEL/tree/master/Misc/data_call_2019 it indicates that the data were reported as NP (not pertinent) and not as zero. I think the problem lies there that it should be zero ? Otherwise with missing data we are going to predict something

**Comment by elfunesto** [comment] 2020-05-14 12:30
> @elfunesto I have checked our notes for data integration in github https://github.com/ices-eg/wg_WGEEL/tree/master/Misc/data_call_2019 it indicates that the data were reported as NP (not pertinent) and not as zero. I think the problem lies there that it should be zero ? Otherwise with missing data we are going to predict something

I have checked in the database, it seems that there is no data at all after 2017 and the last integration was in 2018
`select * from datawg.t_eelstock_eel where  eel_typ_id=4 and eel_cou_code='IE' and eel_year >=2017`
Was dc2019 integrated for Ireland? Anyway, the problem does not seem to lie into the R/shiny side but in the database

**Comment by elfunesto** [comment] 2020-05-14 12:53
I had a look to data call 2018. All landings were already 0 for IE and it had worked, so we can't we just use the file from dc2018, copy and paste values from 2017 and use it for 2018 and 2019?

**Comment by cedricbriandgithub** [comment] 2020-05-20 09:43
This will be fixed in the next datacall, we will provide data, with a note that this year we will integrate the zeros

**Comment by cedricbriandgithub** [comment] 2020-05-20 09:44
This is working now, thanks Hilaire !!

**Closed** 2020-05-20 09:44 UTC
Labels: Shiny app, bug
